---
- hosts: loc
  vars:
    list1: ['Template iterate','Template loop','Template item']
  tasks:
    - name: Ansible template loop example.
      template:
        src: templates_example2.j2
        dest: /home/mdtutorials2/output.txt
        mode: 0777


